import React from 'react';
import './../globals.css';

export const metadata = {
  title: 'MA AS-SIROJI - admin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return <>{children}</>;
}
