import React from 'react';
import './../../globals.css';
import AppshellAdmin from '@/component/__AppshellAdmin';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return <AppshellAdmin>{children}</AppshellAdmin>;
}
